name: deploy to vercel

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm ci
      - run: npm run build
      - run: wget -O vercel.json https://gist.githubusercontent.com/Minettyx/12653992b1ab8a599dd853e5e3d56c67/raw/e2ff4b9acc9d23e26da1ff952e2fb6898747c21e/vercel.json
      - uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./